# Template untuk service
# Variables: {{NAME}}
apiVersion: v1
kind: Service
metadata:
  name: {{NAME}}
  namespace: dejavu-apps
  labels:
    app: {{NAME}}
    managed-by: dejavu
spec:
  selector:
    app: {{NAME}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

